// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKc-bQu9iAg4FumGdl0fUY-7wp-GjVU0I',
    appId: '1:771588035786:web:c31672ce84963b25065033',
    messagingSenderId: '771588035786',
    projectId: 'basic-app-ee9d2',
    authDomain: 'basic-app-ee9d2.firebaseapp.com',
    databaseURL: 'https://basic-app-ee9d2-default-rtdb.firebaseio.com',
    storageBucket: 'basic-app-ee9d2.firebasestorage.app',
    measurementId: 'G-B51ENG65GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXTc6hCYpOBj5kfuqw-zECkedrDoONxs',
    appId: '1:771588035786:android:d594168ea4affae8065033',
    messagingSenderId: '771588035786',
    projectId: 'basic-app-ee9d2',
    databaseURL: 'https://basic-app-ee9d2-default-rtdb.firebaseio.com',
    storageBucket: 'basic-app-ee9d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpiV2ORLnNPlOYGCjaxhEkbznYktbOJRY',
    appId: '1:771588035786:ios:ca602367d5a63221065033',
    messagingSenderId: '771588035786',
    projectId: 'basic-app-ee9d2',
    databaseURL: 'https://basic-app-ee9d2-default-rtdb.firebaseio.com',
    storageBucket: 'basic-app-ee9d2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
